spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/music_analytics}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:dw_init.sql,classpath:performance_indexes.sql
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.jpa.show-sql=false

spotify.redirect-uri=http://127.0.0.1:8080/api/auth/spotify/callback
spotify.frontend-redirect-uri=http://localhost:5173/spotify/callback

spotify.client-id=${SPOTIFY_CLIENT_ID:f7c5f4f18b56409ea0941c2507a7a1cf}
spotify.client-secret=${SPOTIFY_CLIENT_SECRET:7622aa8e36214b609972da3ef95a375b}

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Last.fm API
lastfm.api-key=dummy_key_please_replace
lastfm.api-url=http://ws.audioscrobbler.com/2.0/

spring.rabbitmq.listener.simple.auto-startup=false
spring.rabbitmq.listener.direct.auto-startup=false

