spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/alltimewrapped
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.jpa.show-sql=false